name:                scrabble
version:             0.1.0.0
github:              "ziman/scrabble"
license:             BSD3
author:              "Matus Tejiscak"
maintainer:          "ziman@functor.sk"
copyright:           "2020 Matus Tejiscak"
description:         Online game of Scrabble

dependencies:
- base >= 4.7 && < 5
- text
- transformers
- mtl
- containers
- websockets
- aeson
- aeson-casing
- stm
- bytestring
- random
- vector
- vector-shuffling
- optparse-applicative
- yaml
- ws-game
- bimap
- safe
- microlens-platform

ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N
- -Wall
- -Wextra
- -Werror
- -Wno-name-shadowing

default-extensions:
- LambdaCase
- TypeApplications
- TypeOperators
- ScopedTypeVariables
- DeriveGeneric
- DeriveAnyClass
- DataKinds
- DerivingStrategies
- GeneralizedNewtypeDeriving
- ViewPatterns
- Strict
- FlexibleInstances
- FlexibleContexts
- GADTs
- TypeFamilies
- NamedFieldPuns
- RankNTypes
- MultiParamTypeClasses
- RecordWildCards
- MultiWayIf
- OverloadedStrings
- DuplicateRecordFields

executables:
  backend:
    main:                Main.hs
    source-dirs:         src
